CREATE TABLE IF NOT EXISTS recipin.cmp_userfriendships (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datecreated varchar NOT NULL,
    active boolean NOT NULL,
    pending boolean NOT NULL,
    dateterminated varchar,
    senderid int REFERENCES recipin.appusers (id),
    targetid int REFERENCES recipin.appusers (id)
);