CREATE TABLE IF NOT EXISTS recipin.grocerylist (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    active boolean NOT NULL,
    datecreated varchar NOT NULL,
    datemodified varchar NOT NULL,
    ownerid int REFERENCES recipin.appusers (id)
);