CREATE TABLE IF NOT EXISTS recipin.cmp_recipeingredient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity decimal NOT NULL,
    unit varchar NOT NULL,
    ingredientid int REFERENCES recipin.ingredient (id),
    recipeid int REFERENCES recipin.recipe (id)
);