CREATE TABLE IF NOT EXISTS recipin.cmp_userfriendships (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datecreated varchar NOT NULL,
    active boolean NOT NULL,
    dateterminated varchar,
    firstuserid int REFERENCES recipin.appusers (id),
    seconduserid int REFERENCES recipin.appusers (id)
);