CREATE TABLE IF NOT EXISTS recipin.recipecomments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentbody varchar NOT NULL,
    datecreated varchar NOT NULL,
    recipeid int REFERENCES recipin.recipe (id) NOT NULL,
    authorid int REFERENCES recipin.appusers (id) NOT NULL
);