CREATE TABLE IF NOT EXISTS recipin.cmp_usersubscriptions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collectionid int REFERENCES recipin.collection (id),
    usermemberid int REFERENCES recipin.appusers (id),
    active boolean NOT NULL
);